#!/bin/bash

cat {environment,lexer,parser,expr,compiler}.js |
sed -e '/%CODE%/{r /dev/stdin
d
}' jsg.js.template > build/jsg.js

closure-compiler --language_in=ECMASCRIPT5_STRICT --js build/jsg.js --js_output_file build/jsg.min.js
